/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nombres;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Alfon
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    File file;

    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
        this.btn_doit.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_ruta = new javax.swing.JTextField();
        btn_setPath = new javax.swing.JButton();
        btn_doit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_ruta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_rutaKeyTyped(evt);
            }
        });

        btn_setPath.setText("Find path");
        btn_setPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_setPathActionPerformed(evt);
            }
        });

        btn_doit.setText("DO IT");
        btn_doit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_doitActionPerformed(evt);
            }
        });

        jLabel1.setText("Introduce ruta absoluta a la carpeta:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_doit, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                        .addComponent(txt_ruta)))
                .addGap(18, 18, 18)
                .addComponent(btn_setPath)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_ruta, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_setPath, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_doit)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_setPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_setPathActionPerformed
        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);

        int choosen = jf.showDialog(null, null);
        if (choosen == JFileChooser.APPROVE_OPTION) {
            file = jf.getSelectedFile();
            btn_doit.setEnabled(true);
            txt_ruta.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_btn_setPathActionPerformed

    private void btn_doitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_doitActionPerformed
        // TODO add your handling code here:
        try {
            ArrayList<File> listaFiles = new ArrayList<>();
            String aux = "";
            if (OsUtils.isWindows()) {
                aux = "\\";
            } else {
                aux = "/";
            }
            String[] listaNombres = file.list();
            for (String s : listaNombres) {
                File fiaux = new File(file.getAbsolutePath() + aux + s);
                changeName(fiaux);

            }
            JOptionPane.showConfirmDialog(this, "Operación realizada con éxito.", "Finalizado", JOptionPane.DEFAULT_OPTION);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Ruta no válida", "Error", JOptionPane.ERROR_MESSAGE);
        }

        limpiar();

    }//GEN-LAST:event_btn_doitActionPerformed

    private void changeName(File fi) {
        String aux = "";
        if (OsUtils.isWindows()) {
            aux = "\\";
        } else {
            aux = "/";
        }
        try {
            if (fi.isDirectory()) {
                String[] array = fi.list();
                String nombreArchivo = array[0];
                File foto = (fi.listFiles())[0];
                String nombredir = fi.getName();
                String rutaDir = fi.getAbsolutePath();
                foto.renameTo(new File(fi.getParentFile().getAbsolutePath() + aux + nombredir + getExtension(nombreArchivo)));
                fi.delete();
            }
        } catch (Exception ex) {

            JOptionPane.showMessageDialog(this, "Encontrado directorio sin archivo en: " + fi.getName());
        }

    }

    private void txt_rutaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_rutaKeyTyped
        // TODO add your handling code here:
        btn_doit.setEnabled(true);
    }//GEN-LAST:event_txt_rutaKeyTyped

    private void limpiar() {
        txt_ruta.setText("");
        btn_doit.setEnabled(false);
    }

    private String getExtension(String filename) {
        String aux = "";
        int indice = filename.indexOf(".");
        for (int i = indice; i < filename.length(); i++) {
            aux += filename.charAt(i);
        }

        return aux;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Ventana ven = new Ventana();
                ven.setVisible(true);
                ven.setTitle("TREZE names");

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_doit;
    private javax.swing.JButton btn_setPath;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txt_ruta;
    // End of variables declaration//GEN-END:variables
}
